ignoreFiles:
  - _templates/

title: Jason A. Heppler
description: >-
  Jason Heppler is the senior web developer at the Roy Rosenzweig Center for
  History and New Media at George Mason University.
baseURL: "https://jasonheppler.org/"
copyright: 2008-2024
languageCode: en-us
footnoteReturnLinkContents: " "

permalinks:
  blog: "/:year/:month/:day/:slug/"
  notes: "/:year/:month/:day/:slug/"
  links: "/:year/:month/:day/:slug/"
  archive: "/:slug/"
  page: "/:section/:slug/"

taxonomies:
  category: categories
  tag: tags

params:
  Author:
    name: Jason Heppler
    email: jason@jasonheppler.org

outputs:
  home:
    - HTML
    - RSS
    - JSONFeed
    - JSON
  page:
    - HTML
  section:
    - HTML
    - RSS
    - JSONFeed
  term:
    - HTML
    - RSS
    - JSONFeed

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: nord
    lineNos: false
    tabWidth: 4
    codeFences: false

mediaTypes:
  "application/feed+json":
    suffixes:
      - json

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
  JSONFeed:
    mediaType: "application/feed+json"
    baseName: feed
    isPlainText: true
    notAlternative: false

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

services:
  rss:
    limit: 20

menu:
  nav:
    - name: Publications
      url: /publications/
      weight: 1
    - name: Digital History
      url: /research/
      weight: 2
    - name: Teaching
      url: /courses/
      weight: 3
    - name: Blog
      url: https://social.jasonheppler.org
      weight: 4
    - name: Newsletter
      weight: 5
      url: https://www.tackandink.org/

enableGitInfo: true

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^BLOG_
