title: Jason A. Heppler
description: >-
  Jason Heppler is the senior web developer at the Roy Rosenzweig Center for
  History and New Media at George Mason University.
baseURL: 'https://jasonheppler.org/'
copyright: 2008-2024
languageCode: en-us
footnoteReturnLinkContents: ' '

permalinks:
  blog: '/:year/:month/:day/:slug/'
  archive: '/:slug/'
  page: '/:section/:slug/'

taxonomies:
  category: categories
  tag: tags

author:
  name: Jason Heppler
  email: jason@jasonheppler.org

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
    - RSS
  term:
    - HTML
    - RSS

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: nord
    lineNos: false
    tabWidth: 4
    codeFences: false

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

services:
  rss:
    limit: 20

menu:
  nav:
    - name: Publications
      url: /publications/
      weight: 1
    - name: Digital History
      url: /research/
      weight: 2
    - name: Teaching
      url: /courses/
      weight: 3
    - name: Blog 
      url: https://writing.jasonheppler.org
      weight: 4

enableGitInfo: true
    
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^BLOG_
